"""Configuration centralisée, chargée depuis l'environnement / .env."""
import secrets
from pathlib import Path

from pydantic import model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8", extra="ignore")

    # --- Général ---
    app_name: str = "VulnAegis"
    database_url: str = "sqlite:///./vulnaegis.db"

    # --- Polling ---
    poll_interval_minutes: int = 5
    escalation_check_interval_minutes: int = 60
    escalation_hours: int = 4  # délai avant escalade d'une alerte critique non acquittée
    # EPSS est un fichier statique republié une fois par jour par FIRST.org -> pas besoin de polling
    # fréquent (contrairement au radar PoC GitHub, cf. github_poc_interval_minutes).
    epss_check_interval_minutes: int = 1440
    # Radar PoC GitHub : cadence volontairement courte (fonctionnalité "temps réel"), découplée du
    # poll_interval_minutes principal pour ne pas être ralentie par un gros backfill NVD.
    github_poc_interval_minutes: int = 4

    # --- Sources ---
    nvd_api_key: str | None = None  # optionnel, augmente le quota NVD (5 -> 50 req/30s)
    github_token: str | None = None  # optionnel, augmente le quota GitHub Advisories

    # --- Règles d'alerte ---
    cvss_alert_threshold: float = 7.0
    watchlist_path: Path = Path("watchlist.yaml")
    alert_dedupe_hours: int = 24  # ne pas ré-alerter la même CVE sur le même canal avant N heures

    # --- Score de risque composite (app/scoring.py) ---
    epss_high_risk_threshold: float = 0.5
    # Au-delà de N jours sans signal actif (pas KEV, pas de PoC, EPSS bas), le score composite
    # applique un malus de "staleness" : une vieille CVE théorique pèse moins qu'une CVE fraîche.
    risk_score_stale_days: int = 730

    # --- Canaux de notification ---
    slack_webhook_url: str | None = None
    escalation_slack_webhook_url: str | None = None
    generic_webhook_url: str | None = None  # ex: TheHive, Splunk HEC, QRadar

    smtp_host: str | None = None
    smtp_port: int = 587
    smtp_user: str | None = None
    smtp_password: str | None = None
    smtp_from: str | None = None
    smtp_to: list[str] = []
    smtp_use_tls: bool = True

    # --- API ---
    # Vide par défaut: le dashboard est servi en same-origin et n'a besoin d'aucun header CORS.
    # N'ajouter des origines que pour une intégration cross-origin explicite (ex: un SIEM en iframe).
    api_cors_origins: list[str] = []

    # Clé statique legacy (header X-API-Key), conservée pour compat ascendante. Les déploiements
    # neufs devraient plutôt créer un utilisateur (POST /api/auth/register) puis une clé API
    # via /api/api-keys, qui sont individuellement révocables/traçables. Si ni l'un ni l'autre
    # n'est configuré, les endpoints d'écriture restent ouverts (mode dev/local uniquement).
    api_key: str | None = None

    # --- Auth (JWT + clés API en DB) ---
    jwt_secret_key: str = ""  # si vide, une clé aléatoire est générée au démarrage (voir avertissement)
    jwt_secret_is_autogenerated: bool = False
    jwt_algorithm: str = "HS256"
    jwt_expire_minutes: int = 60

    # --- Enrichissement contexte menace ---
    otx_api_key: str | None = None  # AlienVault OTX DirectConnect, clé gratuite sur otx.alienvault.com
    misp_url: str | None = None  # ex: https://misp.example.org
    misp_api_key: str | None = None

    @model_validator(mode="after")
    def _default_jwt_secret(self) -> "Settings":
        if not self.jwt_secret_key:
            self.jwt_secret_key = secrets.token_urlsafe(48)
            self.jwt_secret_is_autogenerated = True
        return self


settings = Settings()
