import asyncio
import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from app.api import (
    routes_alerts,
    routes_api_keys,
    routes_auth,
    routes_cves,
    routes_poc,
    routes_status,
    routes_watchlist,
    routes_ws,
)
from app.config import settings
from app.database import SessionLocal, init_db
from app.scheduler import start_scheduler, stop_scheduler
from app.watchlist_loader import seed_watchlist
from app.ws import set_main_loop

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
logger = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI):
    set_main_loop(asyncio.get_running_loop())
    init_db()
    db = SessionLocal()
    try:
        seed_watchlist(db)
    finally:
        db.close()
    start_scheduler()
    if not settings.api_key:
        logger.warning(
            "API_KEY non défini : les endpoints d'écriture ne sont pas protégés "
            "(voir README.md > Sécurité avant tout déploiement réseau)."
        )
    if settings.jwt_secret_is_autogenerated:
        logger.warning(
            "JWT_SECRET_KEY non défini : une clé aléatoire a été générée en mémoire pour ce "
            "process - tous les tokens émis seront invalidés au prochain redémarrage, et un "
            "déploiement multi-instance ne pourra pas valider les tokens émis par une autre "
            "instance. À définir explicitement avant tout déploiement réseau/production."
        )
    logger.info("%s démarré", settings.app_name)
    yield
    stop_scheduler()


app = FastAPI(title=settings.app_name, description="Plateforme de détection et d'alerte CVE en temps réel", lifespan=lifespan)

if settings.api_cors_origins:
    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.api_cors_origins,
        allow_methods=["GET", "POST", "DELETE"],
        allow_headers=["Content-Type", "X-API-Key", "Authorization"],
    )


_DOCS_PATHS = ("/docs", "/redoc", "/openapi.json")


@app.middleware("http")
async def security_headers(request: Request, call_next):
    response = await call_next(request)
    response.headers["X-Content-Type-Options"] = "nosniff"
    response.headers["X-Frame-Options"] = "DENY"
    response.headers["Referrer-Policy"] = "no-referrer"
    response.headers["Permissions-Policy"] = "geolocation=(), microphone=(), camera=(), payment=()"
    # Un navigateur ignore ce header s'il n'est pas reçu sur une connexion HTTPS (RFC 6797) : sans
    # effet en dev HTTP, mais protège automatiquement dès qu'un reverse proxy TLS est en place.
    response.headers["Strict-Transport-Security"] = "max-age=63072000; includeSubDomains"
    # Le CSP strict casserait Swagger/Redoc (assets chargés depuis un CDN) : exemptés ici.
    if not request.url.path.startswith(_DOCS_PATHS):
        response.headers["Content-Security-Policy"] = (
            "default-src 'self'; style-src 'self' 'unsafe-inline'; "
            "script-src 'self'; img-src 'self' data:; connect-src 'self'; base-uri 'none'; "
            "frame-ancestors 'none'"
        )
    return response


app.include_router(routes_cves.router)
app.include_router(routes_poc.router)
app.include_router(routes_watchlist.router)
app.include_router(routes_alerts.router)
app.include_router(routes_status.router)
app.include_router(routes_auth.router)
app.include_router(routes_api_keys.router)
app.include_router(routes_ws.router)

app.mount("/", StaticFiles(directory="app/static", html=True), name="dashboard")
